#!/usr/bin/env node
/**
 * dashboard-build.mjs — render plan/INDEX.md + plan/T*.md into dashboard/index.html.
 *
 * Zero dependencies, no network. Node >= 20.
 *
 *   node scripts/dashboard-build.mjs
 *   node scripts/dashboard-build.mjs --lang <code> [--out <path>]
 *   node scripts/dashboard-build.mjs --plan-dir <path> --out <path>   (tests/fixtures)
 *
 * --plan-dir REQUIRES --out: without it the default output path is the tracked
 * dashboard/index.html, and a fixture run would overwrite it.
 *
 * Localization: the page CHROME (title, labels, status badge text, warnings)
 * comes from the DEFAULT_STRINGS table below — English, and English only, in
 * this file. `--lang <code>` merges dashboard/i18n/<code>.json (flat
 * key→string, local-only and gitignored — see dashboard/README.md) over the
 * defaults; missing keys fall back to English. Task ids, titles, notes and
 * Next lines are DATA from plan/*.md and are always rendered verbatim.
 * Localized output defaults to dashboard/index.<code>.html (also gitignored);
 * `--out` overrides the output path.
 *
 * Sources of truth:
 *   - plan/INDEX.md table rows (id, task, status, owner, depends on, note)
 *   - each card's parsed header (see plan/TEMPLATE.md):
 *       **Status:** … · **Owner:** … · **Depends on:** …
 *       PR: #18            (own line; "none yet" means no PR)
 *       **Epic:** …        (cross-session grouping key — T51's roll-up axis)
 *       **Next:** …        (may continue on following lines until a blank one)
 *
 * Where INDEX and a card disagree on status, the dashboard shows BOTH and marks
 * the section as inconsistent — it never silently picks one.
 *
 * The epic roll-up (T51) is built by scanning plan/*.md DIRECTLY — every card
 * file, under both id shapes (legacy T<nn>[<letter>] and session-scoped
 * <YYMMDD-HHMM>-<NNN>; they coexist permanently, see CLAUDE.md "Task ids") —
 * so the task-state summary is generated, never appended by hand per session.
 * Cards without an Epic: line (every pre-T49 card) land in an explicit
 * "(no epic)" bucket rather than being dropped. The roll-up key is NORMALIZED
 * (trim, collapse whitespace, case-fold) so hand-typed spelling drift across
 * sessions does not split one epic in two, and the "never silently picks one"
 * rule above holds for the roll-up as well: a member whose card and INDEX row
 * disagree is marked, counted apart, and shows both. This replaces per-session
 * task-STATUS appends only: OVERVIEW.md's hand-written narrative log (events
 * with no card — incidents, reversed decisions, measurements) is out of scope
 * and untouched by this script.
 */

import { execFileSync } from "node:child_process";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  readdirSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)));
let planDir = join(repoRoot, "plan");
const outDir = join(repoRoot, "dashboard");

const PR_BASE = "https://github.com/TopNetics/bridgeks-app/pull/";

// The two task-id shapes, both permanent (CLAUDE.md "Task ids"): legacy
// T<nn>[<letter>] (T01–T48, T16a–T16e, frozen) and session-scoped
// <YYMMDD-HHMM>-<NNN> minted by scripts/new-task.sh. Every matcher in this
// file accepts BOTH — narrowing to one shape is a bug, not a simplification.
const TASK_ID_PATTERN = "T\\d+[a-z]?|\\d{6}-\\d{4}-\\d{3}";
const CARD_FILE_RE = new RegExp(`^(${TASK_ID_PATTERN})-.+\\.md$`);

const KNOWN_STATUSES = [
  "open",
  "in-progress",
  "in-review",
  "blocked",
  "needs-decision",
  "done",
  "split",
];

// ------------------------------------------------------------------ i18n
//
// Every chrome string lives here, keyed flat. Keys ending in `.html` are
// injected as raw HTML (they carry <code> markup); everything else is
// escaped text. `{file}`, `{index}`, `{card}` and `{n}` are placeholders
// filled with escaped values at render time. The full key list is documented
// in dashboard/README.md — keep the two in sync.
const DEFAULT_STRINGS = {
  title: "bridgeks — plan dashboard",
  "subtitle.html":
    "Rendered from <code>plan/INDEX.md</code> and a scan of every <code>plan/*.md</code> card (both id shapes). Markdown is the source of truth; this page only shows it.",
  "footer.html":
    "Generated by <code>node scripts/dashboard-build.mjs</code> — do not hand-edit. Statuses come from the INDEX table; where a card's own <code>**Status:**</code> header disagrees, both are shown and the section is highlighted.",
  tasks: "Tasks",
  epics: "Epics",
  "epic.none": "(no epic)",
  "epic.cards": "{n} cards",
  "stat.epics": "epics",
  generated: "generated",
  commit: "git HEAD",
  "status.open": "open",
  "status.in-progress": "in-progress",
  "status.in-review": "in-review",
  "status.blocked": "blocked",
  "status.needs-decision": "needs-decision",
  "status.done": "done",
  "status.split": "split",
  "stat.open": "open",
  "stat.in-progress": "in progress",
  "stat.in-review": "in review",
  "stat.blocked": "blocked",
  "stat.needs-decision": "needs decision",
  "stat.done": "done",
  "stat.split": "split",
  "stat.unrecognised": "unrecognised",
  "stat.mismatch": "index ≠ card",
  "label.owner": "owner",
  "label.dependsOn": "depends on",
  "label.pr": "PR",
  "label.card": "card",
  "label.next": "Next",
  "pr.none": "none declared",
  "next.none": "none recorded on the card",
  "warn.cardMissing": "⚠ card file not found — INDEX links {file}",
  "warn.noStatus": "⚠ card has no parseable **Status:** header line",
  "warn.mismatch":
    "⚠ INDEX says “{index}” but the card says “{card}” — both shown, neither trusted",
  "warn.notIndexed":
    "⚠ {file} has no row in plan/INDEX.md — scripts/plan-check.sh fails on this state",
};

// ---------------------------------------------------------------- CLI args

let lang = null;
let outOverride = null;
let planDirOverridden = false;
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--lang" && argv[i + 1]) {
    lang = argv[++i];
  } else if (argv[i] === "--out" && argv[i + 1]) {
    outOverride = argv[++i];
  } else if (argv[i] === "--plan-dir" && argv[i + 1]) {
    // Point the generator at a fixture plan directory (tests). plan-check.sh
    // requires every real plan/*.md to be tracked and indexed, so fixtures
    // cannot live in plan/ itself.
    planDir = resolve(process.cwd(), argv[++i]);
    planDirOverridden = true;
  } else {
    console.error(`dashboard-build: unknown or incomplete argument ${argv[i]}`);
    console.error(
      "usage: node scripts/dashboard-build.mjs [--lang <code>] [--out <path>] [--plan-dir <path>]"
    );
    process.exit(1);
  }
}
if (lang !== null && !/^[a-z]{2,3}(-[A-Za-z0-9]{1,8})*$/.test(lang)) {
  console.error(`dashboard-build: invalid language code "${lang}"`);
  process.exit(1);
}
// --plan-dir is a FIXTURE switch and the default output path is the tracked
// dashboard/index.html: without --out, a fixture run silently renders fixture
// cards over the committed dashboard, which CI then reports as stale against
// the real plan/. The pairing documented in dashboard/README.md is enforced
// here rather than trusted.
if (planDirOverridden && outOverride === null) {
  console.error(
    "dashboard-build: --plan-dir requires --out — refusing to overwrite the tracked dashboard"
  );
  console.error(
    "usage: node scripts/dashboard-build.mjs --plan-dir <path> --out <path>"
  );
  process.exit(1);
}

const STRINGS = { ...DEFAULT_STRINGS };
if (lang) {
  const i18nPath = join(outDir, "i18n", `${lang}.json`);
  if (!existsSync(i18nPath)) {
    console.error(`dashboard-build: translation file not found: ${i18nPath}`);
    console.error(
      "dashboard/i18n/ is local-only (gitignored) — see dashboard/README.md for the key list."
    );
    process.exit(1);
  }
  const overrides = JSON.parse(readFileSync(i18nPath, "utf8"));
  for (const [key, value] of Object.entries(overrides)) {
    if (!(key in DEFAULT_STRINGS)) {
      console.error(
        `dashboard-build: ${lang}.json: unknown key "${key}" ignored`
      );
      continue;
    }
    if (typeof value !== "string") {
      console.error(
        `dashboard-build: ${lang}.json: key "${key}" must be a string`
      );
      process.exit(1);
    }
    STRINGS[key] = value;
  }
}

const htmlLang = lang ?? "en";
const outFile = outOverride
  ? resolve(process.cwd(), outOverride)
  : lang
    ? join(outDir, `index.${lang}.html`)
    : join(outDir, "index.html");

// ---------------------------------------------------------------- helpers

function esc(s) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

/** Escape first, then render a safe subset of inline markdown. */
function inlineMd(s) {
  let e = esc(s);
  e = e.replace(/`([^`]+)`/g, "<code>$1</code>");
  e = e.replace(/\*\*([^*]+(?:\*(?!\*)[^*]*)*)\*\*/g, "<strong>$1</strong>");
  e = e.replace(
    new RegExp(`\\[\\[(${TASK_ID_PATTERN})\\]\\]`, "g"),
    '<a href="#$1">$1</a>'
  );
  return e;
}

/** Escaped chrome string with {placeholder} values (escaped) filled in. */
function chrome(key, params = {}) {
  let out = esc(STRINGS[key]);
  for (const [name, value] of Object.entries(params)) {
    out = out.replaceAll(`{${name}}`, esc(value));
  }
  return out;
}

/** Strip bold markers and trim — for comparing statuses, not for display. */
function normalizeStatus(s) {
  return s.replaceAll("*", "").trim().toLowerCase();
}

/** Leading known-status keyword, or null. "done (cancelled …)" -> "done". */
function statusKeyword(s) {
  const n = normalizeStatus(s);
  for (const k of KNOWN_STATUSES) {
    if (n === k || n.startsWith(k + " ") || n.startsWith(k + ",")) return k;
  }
  return null;
}

/** Display text for a status: localized when the keyword is known, verbatim otherwise. */
function statusText(rawStatus, keyword) {
  if (keyword && KNOWN_STATUSES.includes(keyword)) {
    return STRINGS[`status.${keyword}`];
  }
  return normalizeStatus(rawStatus);
}

/** Split a markdown table row into cells, honouring backslash-escaped pipes. */
function splitRow(line) {
  const cells = [];
  let cur = "";
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === "\\" && line[i + 1] === "|") {
      cur += "|";
      i++;
    } else if (ch === "|") {
      cells.push(cur.trim());
      cur = "";
    } else {
      cur += ch;
    }
  }
  cells.push(cur.trim());
  // A well-formed row starts and ends with a pipe: drop the empty edges.
  if (cells.length && cells[0] === "") cells.shift();
  if (cells.length && cells[cells.length - 1] === "") cells.pop();
  return cells;
}

// ---------------------------------------------------------------- parse INDEX

function parseIndex(indexPath) {
  const lines = readFileSync(indexPath, "utf8").split("\n");
  const rows = [];
  for (const line of lines) {
    if (!line.trimStart().startsWith("|")) continue;
    const cells = splitRow(line.trim());
    if (cells.length < 6) continue;
    if (/^id$/i.test(cells[0])) continue; // header row
    if (/^:?-{2,}:?$/.test(cells[0].replaceAll(" ", ""))) continue; // separator
    const m = cells[0].match(/\[([^\]]+)\]\(([^)]+)\)/);
    rows.push({
      id: m ? m[1] : cells[0],
      cardFile: m ? m[2] : null,
      task: cells[1],
      status: cells[2],
      owner: cells[3],
      dependsOn: cells[4],
      note: cells[5],
    });
  }
  return rows;
}

// ---------------------------------------------------------------- parse card

function parseCard(cardPath) {
  if (!existsSync(cardPath)) return { missing: true };
  const lines = readFileSync(cardPath, "utf8").split("\n");
  const card = {
    missing: false,
    status: null,
    owner: null,
    pr: null,
    prRaw: null,
    epic: null,
    next: null,
  };

  // Header line: **Status:** … · **Owner:** … · **Depends on:** …
  // May wrap onto following lines until PR:/Next:/blank.
  const stIdx = lines.findIndex((l) => /^\*\*Status:\*\*/.test(l));
  if (stIdx !== -1) {
    let header = lines[stIdx];
    for (let i = stIdx + 1; i < lines.length; i++) {
      const l = lines[i];
      if (
        l.trim() === "" ||
        /^\*{0,2}PR\*{0,2}:/.test(l) ||
        /^\*\*Next:\*\*/.test(l)
      )
        break;
      header += " " + l.trim();
    }
    for (const seg of header.split(/\s+·\s+(?=\*\*)/)) {
      const m = seg.match(/^\*\*(.+?):\*\*\s*(.*)$/);
      if (!m) continue;
      const key = m[1].toLowerCase();
      if (key === "status") card.status = m[2].trim();
      if (key === "owner") card.owner = m[2].trim();
    }
  }

  // PR line: `PR: #18` (review-rounds.sh format) or `**PR:** <url>`; "none…" = no PR.
  const prLine = lines.find((l) => /^\*{0,2}PR\*{0,2}:/.test(l));
  if (prLine) {
    const value = prLine.replace(/^\*{0,2}PR\*{0,2}:\s*/, "").trim();
    card.prRaw = value;
    const num = value.match(/#(\d+)/) || value.match(/\/pull\/(\d+)/);
    if (num && !/^none\b/i.test(value)) card.pr = Number(num[1]);
  }

  // **Epic:** line (T49 template field, T51 roll-up axis). Wrapping backticks
  // are stripped for grouping; an unfilled template placeholder (<…>) or a
  // dash counts as absent — the card then lands in the "(no epic)" bucket.
  const epLine = lines.find((l) => /^\*\*Epic:\*\*/.test(l));
  if (epLine) {
    let v = epLine.replace(/^\*\*Epic:\*\*\s*/, "").trim();
    v = v.replace(/^`(.+)`$/s, "$1").trim();
    if (v && !/^<.*>$/s.test(v) && v !== "—" && v !== "-") card.epic = v;
  }

  // **Next:** line, continuing until the first blank line.
  const nxIdx = lines.findIndex((l) => /^\*\*Next:\*\*/.test(l));
  if (nxIdx !== -1) {
    const parts = [lines[nxIdx].replace(/^\*\*Next:\*\*\s*/, "").trim()];
    for (let i = nxIdx + 1; i < lines.length; i++) {
      if (lines[i].trim() === "") break;
      parts.push(lines[i].trim());
    }
    card.next = parts.join(" ").trim();
  }

  return card;
}

// ---------------------------------------------------------------- assemble

const rows = parseIndex(join(planDir, "INDEX.md"));
if (rows.length === 0) {
  console.error("dashboard-build: no data rows found in plan/INDEX.md");
  process.exit(1);
}

const generatedAt = new Date().toISOString();
const head = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
  cwd: repoRoot,
  encoding: "utf8",
}).trim();

const tasks = rows.map((row) => {
  const card = row.cardFile
    ? parseCard(join(planDir, row.cardFile))
    : { missing: true };
  const idxKeyword = statusKeyword(row.status) ?? normalizeStatus(row.status);
  let cardKeyword = null;
  let inconsistent = false;
  if (!card.missing && card.status) {
    cardKeyword = statusKeyword(card.status) ?? normalizeStatus(card.status);
    inconsistent = cardKeyword !== idxKeyword;
  }
  return { row, card, idxKeyword, cardKeyword, inconsistent };
});

const counts = Object.fromEntries(KNOWN_STATUSES.map((s) => [s, 0]));
let otherCount = 0;
for (const t of tasks) {
  if (t.idxKeyword in counts) counts[t.idxKeyword]++;
  else otherCount++;
}
const inconsistentCount = tasks.filter((t) => t.inconsistent).length;

// ------------------------------------------------------- epic roll-up (T51)
//
// Built from the DIRECTORY, not from INDEX rows: a card that exists on disk
// but lost (or never had) its INDEX row is still counted and shown — with a
// warning — never dropped. plan-check.sh fails CI on that state; this page's
// job is to make it visible, not to hide it. Both id shapes are in scope
// (CARD_FILE_RE); a file matching neither shape is still included, keyed by
// its basename, so nothing in plan/ is ever silently invisible.

function scanCards(dir) {
  const cards = [];
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith(".md")) continue;
    if (name === "INDEX.md" || name === "TEMPLATE.md") continue;
    const m = name.match(CARD_FILE_RE);
    cards.push({
      id: m ? m[1] : name.replace(/\.md$/, ""),
      file: name,
      idRecognised: Boolean(m),
      card: parseCard(join(dir, name)),
    });
  }
  return cards;
}

const NO_EPIC = " no-epic"; // sorts nowhere near real keys; rendered via epic.none
const scanned = scanCards(planDir);
const indexedFiles = new Set(rows.map((r) => r.cardFile).filter(Boolean));
const rowByFile = new Map(
  rows.filter((r) => r.cardFile).map((r) => [r.cardFile, r])
);

/**
 * Grouping key for an `Epic:` value: trimmed, internal whitespace collapsed,
 * case-folded. `Marketplace`, `marketplace` and ` Marketplace ` are one epic —
 * cards are written by hand across sessions and the spelling drifts, so the raw
 * string is not an identity. The DISPLAY label is the first spelling seen in
 * scan order (readdir, filename-sorted — deterministic across machines), so the
 * page shows a real spelling from a real card rather than a folded token.
 */
function epicKeyOf(epic) {
  return epic.trim().replace(/\s+/g, " ").toLowerCase();
}

// key (normalized) -> { label (first-seen spelling), members }
const epicsMap = new Map();
for (const s of scanned) {
  const key = s.card.epic === null ? NO_EPIC : epicKeyOf(s.card.epic);
  if (!epicsMap.has(key)) {
    epicsMap.set(key, { label: s.card.epic ?? NO_EPIC, members: [] });
  }
  epicsMap.get(key).members.push(s);
}
// Alphabetical by normalized key, with the "(no epic)" bucket (pre-T49 cards) last.
const epicKeys = [...epicsMap.keys()].filter((k) => k !== NO_EPIC).sort();
if (epicsMap.has(NO_EPIC)) epicKeys.push(NO_EPIC);
// The "(no epic)" bucket is a bucket, not an epic: it is excluded from every
// epic COUNT (heading and stat chip alike) while still being rendered.
const epicCount = epicKeys.filter((k) => k !== NO_EPIC).length;

/**
 * Status of a scanned card as BOTH sources report it — its own `**Status:**`
 * header and its `plan/INDEX.md` row. Round 1 of PR #69: this used to prefer
 * the card and return one keyword, which is exactly the silent pick the Tasks
 * section refuses to make (see this file's header comment and the page footer).
 * `keyword` is null on a disagreement; callers must then show both.
 */
function scannedStatus(s) {
  const row = rowByFile.get(s.file);
  const index = row
    ? (statusKeyword(row.status) ?? normalizeStatus(row.status))
    : null;
  const card = s.card.status
    ? (statusKeyword(s.card.status) ?? normalizeStatus(s.card.status))
    : null;
  const mismatch = index !== null && card !== null && index !== card;
  const agreed = card ?? index;
  return {
    index,
    card,
    mismatch,
    keyword: mismatch
      ? null
      : agreed && KNOWN_STATUSES.includes(agreed)
        ? agreed
        : "unrecognised",
  };
}

/**
 * Per-status counts for one epic, plus a separate `mismatch` tally. A card whose
 * two sources disagree is counted ONLY as a mismatch — counting it under either
 * status would be the silent pick again, one aggregation level up.
 */
function epicStatusCounts(members) {
  const c = {};
  let mismatch = 0;
  for (const m of members) {
    const st = scannedStatus(m);
    if (st.mismatch) mismatch++;
    else c[st.keyword] = (c[st.keyword] ?? 0) + 1;
  }
  return { counts: c, mismatch };
}

const scannedNotIndexed = scanned.filter((s) => !indexedFiles.has(s.file));

// ---------------------------------------------------------------- render

const css = `
*,*::before,*::after{box-sizing:border-box}
:root{
  --bg:#0e1014; --card:#171a20; --card2:#1d2128; --line:#272c35;
  --fg:#e7e9ec; --mut:#98a1ad; --dim:#6d7783;
  --ok:#4ec97f; --warn:#e8b13c; --bad:#e8664d; --link:#63a7f5;
  --blue:#48b6d6; --purple:#a98bf0;
}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--bg);color:var(--fg);
  font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:1180px;margin:0 auto;padding:32px 20px 80px;
  display:grid;grid-template-columns:200px minmax(0,1fr);gap:36px;align-items:start}
nav{position:sticky;top:20px;font-size:13px;max-height:calc(100vh - 40px);overflow-y:auto}
nav h4{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:var(--dim);
  margin:18px 0 6px;font-weight:600}
nav h4:first-child{margin-top:0}
nav a{display:flex;gap:7px;align-items:baseline;padding:3px 0;color:var(--mut)}
nav a:hover{color:var(--fg);text-decoration:none}
nav a .dot{width:6px;height:6px;border-radius:50%;flex:0 0 auto;
  background:var(--dim);margin-top:6px}
nav a .nid{font-variant-numeric:tabular-nums;color:var(--dim);flex:0 0 auto}
nav a .ntxt{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
nav .d-done .dot{background:var(--ok)}
nav .d-needs-decision .dot{background:var(--warn)}
nav .d-blocked .dot{background:var(--bad)}
nav .d-in-progress .dot,nav .d-in-review .dot{background:var(--blue)}
nav .d-split .dot{background:var(--purple)}
main{min-width:0}
a{color:var(--link);text-decoration:none}
a:hover{text-decoration:underline}
code{font:13px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  background:#0b0d11;border:1px solid var(--line);border-radius:4px;padding:.1em .35em}
header{border-bottom:1px solid var(--line);padding-bottom:20px;margin-bottom:28px}
h1{font-size:24px;margin:0 0 6px;letter-spacing:-.01em}
.sub{color:var(--mut);font-size:13px}
.gen{margin-top:10px;font-size:13px;color:var(--fg);display:flex;gap:14px;flex-wrap:wrap}
.gen b{font-weight:600;color:var(--mut)}
.stats{display:flex;flex-wrap:wrap;gap:20px;margin-top:16px}
.stat b{display:block;font-size:22px;line-height:1.2}
.stat span{color:var(--dim);font-size:12px;text-transform:uppercase;letter-spacing:.06em}
.stat.warned b{color:var(--bad)}
h2.sec{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:var(--mut);
  margin:36px 0 14px;font-weight:600}
h2.sec .n{color:var(--dim);font-weight:400}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;
  padding:14px 16px;margin-bottom:10px;scroll-margin-top:16px}
.card.mismatch{border-color:#5a3b2e;background:#1d1613}
.row{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}
.t{font-weight:600;flex:1 1 260px;min-width:0}
.tid{color:var(--dim);font-variant-numeric:tabular-nums;font-size:12px;flex:0 0 auto}
.st{font-size:11px;padding:2px 8px;border-radius:20px;border:1px solid var(--line);
  text-transform:uppercase;letter-spacing:.05em;white-space:nowrap}
.st-open{color:var(--mut)}
.st-in-progress{color:var(--blue);border-color:#1f4351}
.st-in-review{color:var(--purple);border-color:#3c3159}
.st-needs-decision{color:var(--warn);border-color:#5a4a2e}
.st-blocked{color:var(--bad);border-color:#5a3b2e}
.st-done{color:var(--ok);border-color:#26492f}
.st-split{color:var(--purple);border-color:#3c3159}
.st-other{color:var(--warn);border-color:#5a4a2e;text-transform:none}
.st-mismatch{color:var(--bad);border-color:#5a3b2e;text-transform:none}
.badge{display:inline-block;font-size:11px;padding:2px 7px;border-radius:20px;
  border:1px solid var(--line);color:var(--mut);white-space:nowrap}
.own-next{color:var(--blue);border-color:#1f4351}
.own-nest{color:var(--ok);border-color:#26492f}
.own-gp{color:var(--purple);border-color:#3c3159}
.warnline{color:var(--bad);font-size:12px;margin-top:8px;font-weight:600}
.ecounts{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}
.emembers{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}
.emembers a:hover{text-decoration:none;border-color:var(--dim)}
.meta{color:var(--dim);font-size:12px;margin-top:8px;display:flex;gap:14px;flex-wrap:wrap}
.meta b{color:var(--mut);font-weight:600}
.goal{color:var(--fg);font-size:14px;margin-top:8px}
.next{color:var(--mut);font-size:13px;margin-top:8px;padding-left:12px;
  border-left:2px solid var(--line)}
.next b{color:var(--fg);font-weight:600}
footer{margin-top:48px;padding-top:16px;border-top:1px solid var(--line);
  color:var(--dim);font-size:12px}
footer code{font-size:11px}
@media (max-width:860px){
  .wrap{grid-template-columns:1fr;gap:18px;padding:20px 14px 60px}
  nav{position:static;max-height:none;display:flex;gap:16px;overflow-x:auto;
    padding-bottom:10px;border-bottom:1px solid var(--line)}
  nav h4{display:none}
  nav a{white-space:nowrap}
  nav a .ntxt{display:none}
}
`;

/**
 * Status badge. The visible text is localized; the canonical English status
 * word (the vocabulary plan/INDEX.md uses) always travels along in the
 * title/data-status attributes. `textPrefix` is prepended to the visible
 * text only (used for the "card: …" mismatch badge).
 */
function statusBadge(rawStatus, keyword, textPrefix = "") {
  const known = keyword && KNOWN_STATUSES.includes(keyword);
  const cls = known ? `st-${keyword}` : "st-other";
  const canonical = known ? keyword : normalizeStatus(rawStatus);
  const text = textPrefix + statusText(rawStatus, keyword);
  return `<span class="st ${cls}" title="${esc(canonical)}" data-status="${esc(canonical)}">${esc(text)}</span>`;
}

function ownerBadge(owner) {
  const o = normalizeStatus(owner);
  if (o === "" || o === "—" || o === "-") return "";
  let cls = "";
  if (o.startsWith("nextjs")) cls = " own-next";
  else if (o.startsWith("nestjs")) cls = " own-nest";
  else if (o.startsWith("general-purpose")) cls = " own-gp";
  return `<span class="badge${cls}">${esc(o)}</span>`;
}

/**
 * Anchor ids for the epic sections, assigned in one pass so they are unique BY
 * CONSTRUCTION. Normalizing the roll-up key already merges `Marketplace` and
 * `marketplace`, but two genuinely different epics can still slug alike
 * (`Marketplace UI` vs `marketplace-ui`), so a colliding slug takes a numeric
 * suffix in epicKeys order — deterministic, so the anchor of a given epic is
 * stable as long as the set of epics is. `epic-none` is reserved for the
 * "(no epic)" bucket before anything else can claim it.
 */
const epicAnchors = new Map();
{
  const used = new Set(["epic-none"]);
  for (const key of epicKeys) {
    if (key === NO_EPIC) {
      epicAnchors.set(key, "epic-none");
      continue;
    }
    const slug =
      key.replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "unnamed";
    let anchor = `epic-${slug}`;
    for (let n = 2; used.has(anchor); n++) anchor = `epic-${slug}-${n}`;
    used.add(anchor);
    epicAnchors.set(key, anchor);
  }
  // Cheap assertion rather than a trusted invariant: a duplicate DOM id makes
  // every nav link to the second section dead, and silently.
  if (new Set(epicAnchors.values()).size !== epicAnchors.size) {
    console.error("dashboard-build: epic anchor ids are not unique");
    process.exit(1);
  }
}

/** Epic display name (localized for the no-epic bucket, first-seen spelling otherwise). */
function epicName(key) {
  return key === NO_EPIC ? STRINGS["epic.none"] : epicsMap.get(key).label;
}

const navEpics = epicKeys
  .map((key) => {
    const { members } = epicsMap.get(key);
    return `<a href="#${esc(epicAnchors.get(key))}"><span class="dot"></span><span class="nid">${members.length}</span><span class="ntxt">${esc(epicName(key))}</span></a>`;
  })
  .join("\n");

const navItems = tasks
  .map(({ row, idxKeyword }) => {
    const cls = KNOWN_STATUSES.includes(idxKeyword)
      ? `d-${idxKeyword}`
      : "d-other";
    const title = `${row.task} — ${statusText(row.status, idxKeyword)}`;
    return `<a href="#${esc(row.id)}" class="${cls}" title="${esc(title)}"><span class="dot"></span><span class="nid">${esc(row.id)}</span><span class="ntxt">${esc(row.task)}</span></a>`;
  })
  .join("\n");

let statsHtml = KNOWN_STATUSES.map(
  (s) =>
    `<div class="stat"><b>${counts[s]}</b><span>${chrome(`stat.${s}`)}</span></div>`
).join("\n");
if (otherCount > 0) {
  statsHtml += `\n<div class="stat warned"><b>${otherCount}</b><span>${chrome("stat.unrecognised")}</span></div>`;
}
statsHtml += `\n<div class="stat${inconsistentCount ? " warned" : ""}"><b>${inconsistentCount}</b><span>${chrome("stat.mismatch")}</span></div>`;
statsHtml += `\n<div class="stat"><b>${epicCount}</b><span>${chrome("stat.epics")}</span></div>`;

// ------------------------------------------------------------- epics render

const epicSections = epicKeys
  .map((key) => {
    const { members } = epicsMap.get(key);
    const { counts: sc, mismatch } = epicStatusCounts(members);
    let countChips = [...KNOWN_STATUSES, "unrecognised"]
      .filter((k) => sc[k])
      .map((k) => {
        const known = KNOWN_STATUSES.includes(k);
        return `<span class="st ${known ? `st-${k}` : "st-other"}">${sc[k]} ${chrome(known ? `stat.${k}` : "stat.unrecognised")}</span>`;
      })
      .join("\n");
    if (mismatch) {
      countChips += `\n<span class="st st-mismatch">${mismatch} ${chrome("stat.mismatch")}</span>`;
    }
    const chips = members
      .map((m) => {
        const st = scannedStatus(m);
        // On a disagreement the chip carries BOTH statuses and a marker; it
        // never renders one of them as if it were the answer.
        const cls = st.mismatch
          ? "st-mismatch"
          : KNOWN_STATUSES.includes(st.keyword)
            ? `st-${st.keyword}`
            : "st-other";
        const title = st.mismatch
          ? `plan/${m.file} — ${STRINGS["stat.mismatch"]}: ${st.index} / ${st.card}`
          : `plan/${m.file} — ${st.keyword}`;
        const data = st.mismatch
          ? `data-status-index="${esc(st.index)}" data-status-card="${esc(st.card)}"`
          : `data-status="${esc(st.keyword)}"`;
        const text = st.mismatch ? `${m.id} ⚠` : m.id;
        // Only indexed cards have a task section to link to; a scanned-only
        // card renders as plain text plus the warning line below.
        return indexedFiles.has(m.file)
          ? `<a class="st ${cls}" href="#${esc(m.id)}" title="${esc(title)}" ${data}>${esc(text)}</a>`
          : `<span class="st ${cls}" title="${esc(title)}" ${data}>${esc(text)}</span>`;
      })
      .join("\n");
    const warns = members
      .flatMap((m) => {
        const out = [];
        if (!indexedFiles.has(m.file)) {
          out.push(
            `<div class="warnline">${chrome("warn.notIndexed", { file: `plan/${m.file}` })}</div>`
          );
        }
        const st = scannedStatus(m);
        if (st.mismatch) {
          out.push(
            `<div class="warnline"><code>plan/${esc(m.file)}</code> ${chrome("warn.mismatch", { index: st.index, card: st.card })}</div>`
          );
        }
        return out;
      })
      .join("\n");
    return `<div class="card${mismatch ? " mismatch" : ""}" id="${esc(epicAnchors.get(key))}">
<div class="row"><div class="t">${esc(epicName(key))}</div><span class="badge">${chrome("epic.cards", { n: String(members.length) })}</span></div>
<div class="ecounts">${countChips}</div>
<div class="emembers">${chips}</div>
${warns}
</div>`;
  })
  .join("\n");

const sections = tasks
  .map(({ row, card, idxKeyword, cardKeyword, inconsistent }) => {
    const badges = [statusBadge(row.status, idxKeyword)];
    if (inconsistent && card.status) {
      badges.push(
        statusBadge(card.status, cardKeyword, `${STRINGS["label.card"]}: `)
      );
    }
    const metaBits = [];
    metaBits.push(
      `<span><b>${chrome("label.owner")}:</b> ${ownerBadge(row.owner) || esc(normalizeStatus(row.owner) || "—")}</span>`
    );
    metaBits.push(
      `<span><b>${chrome("label.dependsOn")}:</b> ${inlineMd(row.dependsOn || "—")}</span>`
    );
    if (card.pr) {
      metaBits.push(
        `<span><b>${chrome("label.pr")}:</b> <a href="${PR_BASE}${card.pr}">#${card.pr}</a></span>`
      );
    } else {
      metaBits.push(
        `<span><b>${chrome("label.pr")}:</b> ${esc(card.prRaw || STRINGS["pr.none"])}</span>`
      );
    }
    if (row.cardFile) {
      metaBits.push(
        `<span><b>${chrome("label.card")}:</b> <code>plan/${esc(row.cardFile)}</code></span>`
      );
    }

    let warn = "";
    if (card.missing) {
      warn = `<div class="warnline">${chrome("warn.cardMissing", { file: row.cardFile ?? "(no file)" })}</div>`;
    } else if (!card.status) {
      warn = `<div class="warnline">${chrome("warn.noStatus")}</div>`;
    } else if (inconsistent) {
      warn = `<div class="warnline">${chrome("warn.mismatch", { index: normalizeStatus(row.status), card: normalizeStatus(card.status) })}</div>`;
    }

    const nextHtml = card.next
      ? `<div class="next"><b>${chrome("label.next")}:</b> ${inlineMd(card.next)}</div>`
      : `<div class="next"><b>${chrome("label.next")}:</b> <em>${chrome("next.none")}</em></div>`;

    return `<div class="card${inconsistent || card.missing ? " mismatch" : ""}" id="${esc(row.id)}">
<div class="row"><span class="tid">${esc(row.id)}</span><div class="t">${inlineMd(row.task)}</div>${badges.join("")}</div>
${warn}
<div class="meta">${metaBits.join("\n")}</div>
<div class="goal">${inlineMd(row.note)}</div>
${nextHtml}
</div>`;
  })
  .join("\n");

const html = `<!doctype html>
<html lang="${esc(htmlLang)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${chrome("title")}</title>
<style>${css}</style></head><body><div class="wrap">
<nav>
<h4>${chrome("epics")}</h4>
${navEpics}
<h4>${chrome("tasks")}</h4>
${navItems}
</nav>
<main>
<header>
<h1>${chrome("title")}</h1>
<div class="sub">${STRINGS["subtitle.html"]}</div>
<div class="gen"><span><b>${chrome("generated")}</b> <code>${esc(generatedAt)}</code></span><span><b>${chrome("commit")}</b> <code>${esc(head)}</code></span></div>
<div class="stats">
${statsHtml}
</div></header>
<h2 class="sec" id="epics">${chrome("epics")} <span class="n">${epicCount}</span></h2>
${epicSections}
<h2 class="sec" id="tasks">${chrome("tasks")} <span class="n">${tasks.length}</span></h2>
${sections}
<footer>${STRINGS["footer.html"]}</footer>
</main>
</div></body></html>
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, html);

console.log(`dashboard-build: ${tasks.length} tasks -> ${outFile}`);
console.log(
  `  HEAD ${head} · generated ${generatedAt} · lang ${htmlLang}${lang ? ` (dashboard/i18n/${lang}.json)` : ""}`
);
console.log(
  `  status counts: ${KNOWN_STATUSES.map((s) => `${s}=${counts[s]}`).join(" ")}${otherCount ? ` other=${otherCount}` : ""}`
);
console.log(`  index/card status mismatches: ${inconsistentCount}`);
console.log(
  `  cards scanned: ${scanned.length} from ${planDir} (INDEX rows: ${rows.length}${scannedNotIndexed.length ? `; NOT indexed: ${scannedNotIndexed.map((s) => s.file).join(", ")}` : ""})`
);
console.log(
  `  epic roll-up: ${epicCount} epic(s)${epicsMap.has(NO_EPIC) ? ` + a "(no epic)" bucket of ${epicsMap.get(NO_EPIC).members.length}` : ""}`
);
for (const key of epicKeys) {
  const { members } = epicsMap.get(key);
  const { counts: sc, mismatch } = epicStatusCounts(members);
  const parts = [...KNOWN_STATUSES, "unrecognised"]
    .filter((k) => sc[k])
    .map((k) => `${k}=${sc[k]}`);
  if (mismatch) parts.push(`mismatch=${mismatch}`);
  console.log(
    `    ${key === NO_EPIC ? "(no epic)" : epicName(key)}: ${members.length} card(s) — ${parts.join(" ")} — ${members.map((m) => m.id).join(" ")}`
  );
}
